# Generated by Django 5.1 on 2024-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone', models.CharField(max_length=12)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Appointment_Doctor', models.CharField(max_length=100)),
                ('Appointment_dept', models.CharField(max_length=50)),
                ('Appointment_Date', models.DateField()),
                ('Appointment_Time', models.TimeField()),
                ('Token', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_and_Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Catagory', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('Certificate', models.FileField(blank=True, null=True, upload_to='Certificate')),
                ('Start_Duty_time', models.TimeField(blank=True, null=True)),
                ('End_Duty_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=12)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to='patients_photos/')),
                ('Consultent_Doctor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Catagory', models.CharField(max_length=50)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Password', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Catagory', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(max_length=50, null=True)),
                ('Image', models.ImageField(null=True, upload_to='profile/')),
                ('Certificate', models.FileField(blank=True, null=True, upload_to='Certificate')),
                ('Start_Duty_time', models.TimeField(null=True)),
                ('End_Duty_time', models.TimeField(null=True)),
            ],
        ),
    ]
