# Generated by Django 5.1 on 2024-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0002_alter_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Token',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
