# Generated by Django 5.1 on 2024-09-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0003_alter_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Token',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
